name: gym
channels:
  - conda-forge
  - Microsoft
  - defaults
dependencies:
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=openblas
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - cloudpickle=3.1.1=py310hca03da5_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310h7f4e7e6_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.16.2=hda038a8_0
  - debugpy=1.8.17=py310h7b404bc_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dill=0.4.0=pyhd8ed1ab_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - farama-notifications=0.0.4=py310hca03da5_0
  - fluidsynth=2.3.7=h80fea77_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.0=py310hf4fd40f_0
  - freetype=2.14.1=hce30654_0
  - gettext=0.25.1=h3dcc1bd_0
  - gettext-tools=0.25.1=h493aca8_0
  - graphite2=1.3.14=hec049ff_2
  - gymnasium=0.28.1=py310hca03da5_1
  - harfbuzz=11.3.3=hcb8449c_0
  - icu=75.1=hfee45f7_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh92f572d_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jax-jumpy=1.0.0=py310hca03da5_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - kiwisolver=1.4.9=py310h92dc006_1
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libasprintf=0.25.1=h493aca8_0
  - libasprintf-devel=0.25.1=h493aca8_0
  - libavif16=1.3.0=hb06b76e_2
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcxx=21.1.2=hf598326_0
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libflac=1.4.3=hb765f3a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgettextpo=0.25.1=h493aca8_0
  - libgettextpo-devel=0.25.1=h493aca8_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.84.2=hdc2269c_0
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libmad=0.15.1b=h1a8c8d9_1001
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=hf2bb037_0
  - libopus=1.5.2=h48c0fde_0
  - libpng=1.6.50=h280e0eb_1
  - libsndfile=1.2.2=h9739721_1
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.4=h4237e3c_0
  - libtiff=4.7.1=h7dc4979_0
  - libusb=1.0.29=hbc156a2_0
  - libvorbis=1.3.7=h81086ad_2
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxgboost=3.1.2=cpu_h64a644d_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=20.1.8=he822017_0
  - matplotlib=3.10.6=py310hb6292c7_1
  - matplotlib-base=3.10.6=py310h0181960_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mpg123=1.32.9=hf642e45_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=1.26.4=py310h901140f_1
  - numpy-base=1.26.4=py310hae06d03_1
  - openjpeg=2.5.4=hbfb3c88_0
  - openpyxl=3.1.5=py310h2772267_2
  - openssl=3.6.0=h5503f6c_0
  - opusfile=0.12=h5643135_2
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h25f4b65_1
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.42=h26f9a81_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py310h5de80a5_3
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - platformdirs=4.4.0=pyhcf101f3_0
  - portaudio=19.6.0=h13dd4ca_9
  - portmidi=2.0.6=h286801f_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.0=py310hfe3a0ae_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-xgboost=3.1.2=cpu_pyh053a271_0
  - pygame=2.6.1=py310h3944dc2_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.10.18=h6cefb37_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.1.0=py310hc4a7dca_0
  - qhull=2020.2=h420ef59_5
  - rav1e=0.7.1=h0716509_3
  - readline=8.3=h0b18652_0
  - scikit-learn=1.7.2=py310h660f142_0
  - scipy=1.15.3=py310h132fc3c_1
  - sdl2=2.32.56=h248ca61_0
  - sdl2_image=2.8.2=h376e2e1_1
  - sdl2_mixer=2.6.3=h4fe3bdc_1
  - sdl2_ttf=2.24.0=h49b19f9_1
  - sdl3=3.2.22=he22eeb8_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=h79febb2_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py310hfdc7867_1
  - svt-av1=3.1.2=h12ba402_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.2=py310h7bdd564_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py310h7bdd564_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xgboost=3.1.2=cpu_pyhb39878e_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - certifi==2025.10.5
      - filelock==3.20.0
      - fsspec==2025.10.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.4.2
      - sympy==1.14.0
      - torch==2.9.0
      - torchaudio==2.9.0
      - torchvision==0.24.0
prefix: /opt/anaconda3/envs/gym
