name: ml
channels:
  - conda-forge
  - Microsoft
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=openblas
  - brotli-python=1.2.0=py313h79bbab8_0
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py313hc845a76_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - cpython=3.13.9=py313hd8ed1ab_101
  - debugpy=1.8.17=py313hc37fe24_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=hec049ff_0
  - farama-notifications=0.0.4=pyhd8ed1ab_0
  - gymnasium=1.2.1=np2py313hb0da385_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jax-jumpy=1.0.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.1=py313hca03da5_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kagglehub=0.3.8=pyhd8ed1ab_0
  - krb5=1.21.3=h237132a_0
  - libcxx=21.1.5=hf598326_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libopenblas=0.3.29=hea593b9_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.51.0=h8adb53f_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=20.1.8=he822017_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.3.1=py313h50dd0cd_0
  - numpy-base=2.3.1=py313h2506b34_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313h7d16b84_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.3=pyh145f28c_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py313h9734d34_0
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.9=hfc2f54d_101_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.13.9=h4df99d1_101
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyzmq=27.1.0=py312hd65ceae_0
  - readline=8.3=h0b18652_0
  - requests=2.32.5=pyhd8ed1ab_0
  - scikit-learn=1.7.1=py313h2309ff8_0
  - scipy=1.16.0=py313h224531d_1
  - setuptools=73.0.1=pyhd8ed1ab_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=h81ab1b7_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - threadpoolctl=3.5.0=py313h7eb115d_0
  - tk=8.6.13=h892fb3f_2
  - tornado=6.5.2=py313h6535dbc_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h8359307_2
  - zstandard=0.23.0=py313hcdf3177_3
  - pip:
      - beautifulsoup4==4.14.2
      - bs4==0.0.2
      - curl-cffi==0.13.0
      - dotenv==0.9.9
      - filelock==3.20.0
      - fsspec==2025.10.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.5
      - pillow==12.0.0
      - python-dotenv==1.2.1
      - pyzill==1.0.3
      - soupsieve==2.8
      - sympy==1.14.0
      - torch==2.9.0
      - torchaudio==2.9.0
      - torchvision==0.24.0
prefix: /opt/anaconda3/envs/ml
